PENPals/PENPals.Web/Controllers/CoreRecordController.cs
/* This file was automatically generated by the MNIT.Web.PENPalsUI T4 Template
You can safely remove this section once you are happy
 
 The following connection settings were used to generate this file
 
     Connection String Name: `PENPals`
     Provider:               `System.Data.SqlClient`
     Connection String:      `data source=localhost;initial catalog=PENPals_DEV;persist security info=True;Trusted_Connection=true;multipleactiveresultsets=True;App=PENPals`
     Include Views:          `True`
*/
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PENPals.Web.Attributes;
using PENPals.Domain;
using PENPals.Domain.Models;
using PENPals.Domain.Interfaces;
using MNIT.Web.Security.Models;

namespace PENPals.Web.Controllers
{

	/// <summary>
	/// A controller which represents the CoreRecord table.
	/// </summary>
	[Authorize]
	public partial class CoreRecordController : Controller
	{
		private readonly IReferenceData _refData;
		private readonly IRepository _repo;

		public CoreRecordController(IReferenceData refData, IRepository repo)
		{
			_refData = refData;
			_repo = repo;
		}


		[HttpGet]
		[MenuItem(DisplayName = "CoreRecords")]
		public async Task<ActionResult> Index()
		{
			var records = await _repo.Get<CoreRecord>();
			return View(records);
		}


		[HttpGet]
		public async Task<ActionResult> Edit(int id)
		{
			var record = await _repo.GetByIdAsync<int, CoreRecord>(id);
			SetupReferenceDataForEdit(record.PatientId);
			ViewBag.CurrentRecordHashCode = record.GetHashCode();
			return View(record);
		}

		[HttpPost]
		public async Task<ActionResult> Edit(CoreRecord data, int? CurrentRecordHashCode)
		{
			var model = await _repo.GetByIdAsync<int, CoreRecord>(data.ID);
			if (CurrentRecordHashCode.HasValue && model != null && CurrentRecordHashCode != model.GetHashCode())
			{
				return new HttpStatusCodeResult(System.Net.HttpStatusCode.Conflict, string.Format("Record {0} has been changed by another user.", data.ID));
			}

			if (model == null)
			{
				model = new CoreRecord
				{
					CoreRecordId = System.Guid.NewGuid()
				};
			}


			model.ChangedById = (User.Identity as MnitIdentity<int>).ID;
			//Remove the insert only fields if we're dealing with a new record
			if (data.ID == 0)
			{
				ModelState.Remove("ID");
				ModelState.Remove("CoreRecordId");
				ModelState.Remove("ChangedAt");
				ModelState.Remove("ChangedById");
				ModelState.Remove("BaseVersion");
				ModelState.Remove("CurrentRecordHashCode");
			}
			var tryUpdateModelExclusions = new string[] { "ID", "CoreRecordId", "ChangedAt", "ChangedById", "BaseVersion" };
			if (data.ID != 0) //existing record
			{
				tryUpdateModelExclusions = null;
			}
			if (TryUpdateModel(model, "", null, tryUpdateModelExclusions))
			{
				await _repo.InsertForInsertOnly(model, (User.Identity as MnitIdentity<int>).ID);
				return RedirectToAction("Index");
			}

			//model bind error
			SetupReferenceDataForEdit(model.PatientId);
			ViewBag.CurrentRecordHashCode = CurrentRecordHashCode;
			return View(model);
		}

		[HttpGet]
		public async Task<ActionResult> New()
		{
			await Task.Yield();

			SetupReferenceDataForEdit(new int?());
			return View("Edit", new CoreRecord());
		}

		[HttpPost]
		public async Task<ActionResult> Delete(int id, int? CurrentRecordHashCode)
		{
			//todo make sure we get the latest record for this id
			var model = await _repo.GetByIdAsync<int, CoreRecord>(id);
			if (!CurrentRecordHashCode.HasValue && model != null && CurrentRecordHashCode != model.GetHashCode())
			{
				return new HttpStatusCodeResult(System.Net.HttpStatusCode.Conflict, string.Format("Record {0} has been changed by another user.", id));
			}


			await _repo.DeleteForInsertOnly<int, CoreRecord>(id, (User.Identity as MnitIdentity<int>).ID);
			return RedirectToAction("Index");
		}


		private async void SetupReferenceDataForEdit(int? selectedPatientId)
		{
			await Task.Yield();
		}

	}
}

PENPals/PENPals.Web/Views/CoreRecord/Edit.cshtml
@* This file was automatically generated by the MNIT.Web.PENPalsUI T4 Template
You can safely remove this section once you are happy
 
 The following connection settings were used to generate this file
 
     Connection String Name: `PENPals`
     Provider:               `System.Data.SqlClient`
     Connection String:      `data source=localhost;initial catalog=PENPals_DEV;persist security info=True;Trusted_Connection=true;multipleactiveresultsets=True;App=PENPals`
     Include Views:          `True`
*@

@model PENPals.Domain.Models.CoreRecord

@{
    ViewBag.Title = "Edit CoreRecords";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit CoreRecord</h2>

@using (Html.BeginForm("Edit", "CoreRecord"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<input type="hidden" name="CurrentRecordHashCode" id="CurrentRecordHashCode" value='@(ViewBag.CurrentRecordHashCode ?? "null")' />


        @Html.HiddenFor(model => model.ID)

		<div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.BaseVersion)

        @Html.HiddenFor(model => model.ChangedById)

        @Html.HiddenFor(model => model.ChangedAt)
       
		<div class="form-group">
            @Html.LabelFor(model => model.Patient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.PatientId, 
				ViewBag.refPatients as SelectList, 
                "Please select...",
				new { @class = "form-control", 
				required = "required" })

				@Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>


		<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Delete", "CoreRecord"))
{
    @Html.AntiForgeryToken()

	<input type="hidden" name="CurrentRecordHashCode" id="CurrentRecordHashCode" value='@(ViewBag.CurrentRecordHashCode ?? "null")' />
   
	
	<input type="hidden" name="id" id="id" value="@Model.ID" />
	
    <div class="form-horizontal">
        <div class="form-group">
			<div class="col-md-offset-2 col-md-4">
                @Html.ActionLink("Back to List", "Index", "CoreRecord")
            </div>
			@if(Model.ID != 0)
			{
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Delete this record" class="btn btn-danger" />
            </div>
			}
        </div>
	</div>
}